// <auto-generated />
namespace THEcapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class forthelols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forthelols));
        
        string IMigrationMetadata.Id
        {
            get { return "201801292058000_for the lols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
