// <auto-generated />
namespace THEcapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fuckina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fuckina));
        
        string IMigrationMetadata.Id
        {
            get { return "201801310429358_fuckin a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
